[package]
name = "littledb"
version = "0.1.0"
edition = "2024"

[dependencies]
# Serde: Serialization/Deserialization framework
serde = { version = "1.0", features = ["derive"] }
# Bincode: Fast binary serialization format
bincode = "1.3"